name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fortran compiler and build tools
        run: sudo apt-get update && sudo apt-get install -y gfortran make

      - name: Compile the Fortran project
        run: make

      - name: Verify executable
        run: ls -l your_executable_name || (echo "Executable not found!" && exit 1)
