name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Fortran compiler and build tools
      run: sudo apt-get update && sudo apt-get install -y gfortran build-essential automake autoconf

    - name: Ensure configure script is executable
      run: chmod +x configure

    - name: Run configure script
      run: |
        set -e
        ./configure

    - name: Compile the Fortran project
      run: |
        set -e
        make

    - name: Run check
      run: |
        set -e
        make check

    - name: Run distcheck
      run: |
        set -e
        make distcheck


    - name: Run distcheck
      run: make distcheck
